# Generated by Django 6.0.5 on 2026-05-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trainer_code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'trainers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_id', models.IntegerField()),
                ('proficiency_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trainer_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], default='Bank Transfer', max_length=50)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('hours_billed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='trainermgmt.trainer')),
            ],
            options={
                'db_table': 'trainer_payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
