# Generated by Django 6.0.5 on 2026-05-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academic_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anisha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'anisha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentResults',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('assessment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=150)),
                ('assessment_type', models.CharField(max_length=60)),
                ('total_marks', models.PositiveIntegerField()),
                ('passing_marks', models.PositiveIntegerField()),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'assessments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('attendance_photo', models.CharField(blank=True, max_length=100, null=True)),
                ('marked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('browser_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=30, unique=True)),
                ('batch_name', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=80)),
                ('subject_short_name', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(max_length=80, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_url', models.CharField(max_length=200)),
                ('verification_code', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('certification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=150)),
                ('issuing_authority', models.CharField(max_length=150)),
                ('certificate_no', models.CharField(max_length=80)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'certifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=20, unique=True)),
                ('city_name', models.CharField(max_length=120)),
                ('state_name', models.CharField(max_length=120)),
                ('country_name', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('complaint_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('complaint_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'complaints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=20, unique=True)),
                ('category_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'course_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursesTcm',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('course_name', models.CharField(max_length=150)),
                ('course_image', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('duration_hours', models.PositiveIntegerField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'courses_tcm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTrainers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'course_trainers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cards', models.CharField(blank=True, max_length=100, null=True)),
                ('isenabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_activity_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardActivitylogTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboard_activitylog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardDashboardcard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_count', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboard_dashboardcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('is_read', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboard_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardQuickLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=60)),
                ('colour', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboard_quick_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeePayments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=30)),
                ('receipt_no', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fee_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_no', models.IntegerField()),
            ],
            options={
                'db_table': 'floors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GauravUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('is_email_verified', models.IntegerField()),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gaurav_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GauravUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gaurav_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GauravUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gaurav_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('gender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender_code', models.CharField(max_length=20, unique=True)),
                ('gender_name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostelmgmtBlock',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hostelmgmt_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostelmgmtFloor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_no', models.IntegerField()),
                ('block_id', models.IntegerField()),
            ],
            options={
                'db_table': 'hostelmgmt_floor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostelmgmtHostel',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_code', models.CharField(max_length=20, unique=True)),
                ('hostel_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hostelmgmt_hostel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostelmgmtVisitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('visitor_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hostelmgmt_visitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_code', models.CharField(max_length=20, unique=True)),
                ('hostel_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hostels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('resolved_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maintenance_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('file_type', models.CharField(max_length=40)),
                ('file_url', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=150)),
                ('module_image', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('sequence_no', models.PositiveIntegerField()),
                ('duration_hours', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantGuardians',
            fields=[
                ('guardian_id', models.AutoField(primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participant_guardians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('admission_no', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramCourses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'program_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('program_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('program_code', models.CharField(max_length=30, unique=True)),
                ('program_name', models.CharField(max_length=150)),
                ('program_image', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramTrainers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=200)),
                ('assigned_date', models.DateField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'program_trainers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomAllocations',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('bed_number', models.IntegerField()),
                ('allocation_date', models.DateField()),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('person_type', models.CharField(max_length=10)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('actual_checkout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_allocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomTransfers',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('request_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'room_transfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('room_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type_code', models.CharField(max_length=20, unique=True)),
                ('room_type_name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'room_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_topic', models.CharField(max_length=200)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('recording_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_master_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=80)),
                ('status_code', models.CharField(max_length=40)),
                ('status_name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'status_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGuardians',
            fields=[
                ('guardian_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('occupation', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'student_guardians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('join_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsAttendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('student_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'students_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_global', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('is_read', models.IntegerField()),
                ('student_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('max_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('remarks', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('student_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'students_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=68, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerPayments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('hours_billed', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trainer_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('trainer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trainer_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('join_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'trainers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerSkills',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_id', models.PositiveIntegerField()),
                ('proficiency_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trainer_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_role_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('visitor_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('student_name', models.CharField(max_length=100)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visitor_email', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'visitors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('waiting_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_type', models.CharField(max_length=10)),
                ('person_id', models.CharField(max_length=50)),
                ('person_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('added_on', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'waiting_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], default='Bank Transfer', max_length=50)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('hours_billed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billingmgmt.trainers')),
            ],
            options={
                'db_table': 'trainer_payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
