# Generated by Django 6.0.5 on 2026-05-29 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingmgmt', '0002_alter_trainerpayment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_title', models.CharField(help_text='A descriptive title for the bill.', max_length=255)),
                ('bill_number', models.CharField(help_text='Unique bill/invoice number.', max_length=100, unique=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the bill in INR.', max_digits=12)),
                ('training_program', models.CharField(help_text='Name of the training program this bill is associated with.', max_length=255)),
                ('bill_pdf', models.FileField(help_text='Uploaded PDF copy of the bill.', upload_to='bills/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the bill was first uploaded.')),
                ('current_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_ACCOUNTS_REVIEW', 'Under Accounts Review'), ('APPROVED_BY_ACCOUNTS', 'Approved by Accounts'), ('REJECTED_BY_ACCOUNTS', 'Rejected by Accounts'), ('UNDER_TRAINER_ADMIN_REVIEW', 'Under Trainer Admin Review'), ('PAYMENT_CLEARED', 'Payment Cleared'), ('REJECTED_BY_TRAINER_ADMIN', 'Rejected by Trainer Admin')], default='SUBMITTED', help_text='Current workflow status of the bill.', max_length=40)),
                ('final_approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the bill received final approval and payment was cleared.', null=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Latest remarks or reason for rejection.')),
                ('trainer', models.ForeignKey(help_text='The trainer who submitted this bill.', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(help_text='Short description of the action (e.g. "Approved by Accounts").', max_length=100)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional remarks associated with this action.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action was recorded.')),
                ('action_by', models.ForeignKey(help_text='The user who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(help_text='The bill this history entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='billingmgmt.bill')),
            ],
            options={
                'verbose_name': 'Bill History',
                'verbose_name_plural': 'Bill Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short notification headline.', max_length=255)),
                ('message', models.TextField(help_text='Full notification body.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created.')),
                ('user', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='billing_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='trainerpayment',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='AcademicYears',
        ),
        migrations.DeleteModel(
            name='Anisha',
        ),
        migrations.DeleteModel(
            name='AssessmentResults',
        ),
        migrations.DeleteModel(
            name='Assessments',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AuditLogs',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='Batches',
        ),
        migrations.DeleteModel(
            name='Blocks',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='CourseCategories',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='CoursesTcm',
        ),
        migrations.DeleteModel(
            name='CourseTrainers',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardActivityLog',
        ),
        migrations.DeleteModel(
            name='DashboardActivitylogTable',
        ),
        migrations.DeleteModel(
            name='DashboardDashboardcard',
        ),
        migrations.DeleteModel(
            name='DashboardNotification',
        ),
        migrations.DeleteModel(
            name='DashboardQuickLinks',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Enrollments',
        ),
        migrations.DeleteModel(
            name='FeePayments',
        ),
        migrations.DeleteModel(
            name='Floors',
        ),
        migrations.DeleteModel(
            name='GauravUser',
        ),
        migrations.DeleteModel(
            name='GauravUserGroups',
        ),
        migrations.DeleteModel(
            name='GauravUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Genders',
        ),
        migrations.DeleteModel(
            name='HostelmgmtBlock',
        ),
        migrations.DeleteModel(
            name='HostelmgmtFloor',
        ),
        migrations.DeleteModel(
            name='HostelmgmtHostel',
        ),
        migrations.DeleteModel(
            name='HostelmgmtVisitor',
        ),
        migrations.DeleteModel(
            name='Hostels',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequests',
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='ParticipantGuardians',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='ProgramCourses',
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
        migrations.DeleteModel(
            name='ProgramTrainers',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='RoomAllocations',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='RoomTransfers',
        ),
        migrations.DeleteModel(
            name='RoomTypes',
        ),
        migrations.DeleteModel(
            name='Sessions',
        ),
        migrations.DeleteModel(
            name='StatusMaster',
        ),
        migrations.DeleteModel(
            name='StudentGuardians',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='StudentsAttendance',
        ),
        migrations.DeleteModel(
            name='StudentsNotification',
        ),
        migrations.DeleteModel(
            name='StudentsResult',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TrainerPayments',
        ),
        migrations.DeleteModel(
            name='Trainers',
        ),
        migrations.DeleteModel(
            name='TrainerSkills',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
        migrations.DeleteModel(
            name='TrainerPayment',
        ),
    ]
