# Generated by Django 6.0.5 on 2026-05-28 10:47

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RBACPermissionProxy',
        ),
        migrations.CreateModel(
            name='RBACPermissionProxy',
            fields=[
            ],
            options={
                'permissions': (('can_view_admin_dashboard', 'Can view central security dashboard layout'), ('can_view_permission_matrix', 'Can view global cross-reference matrix grid'), ('can_modify_permissions', 'Can alter granular privileges or override tokens'), ('can_manage_roles', 'Can create, update, or delete system groups'), ('can_assign_roles', 'Can map user accounts to defined groups'), ('can_view_management_reports', 'Can read high-level analytical business summaries'), ('can_approve_requests', 'Can authorize institutional operational overrides'), ('can_view_finance_dashboard', 'Can read accounting ledgers and payment histories'), ('can_manage_finance', 'Can process invoices and update payment parameters'), ('can_view_qa_logs', 'Can read automated testing output metrics and system reports'), ('can_manage_qa_tickets', 'Can log, modify, or track software verification modules'), ('can_view_student_profiles', 'Can read student records and profiles (Lower Level Access)'), ('can_view_trainer_profiles', 'Can read trainer contact parameters (Lower Level Access)'), ('can_view_course_details', 'Can read syllabus blueprints and batch timings (Lower Level Access)'), ('can_view_hostel_status', 'Can read room vacancy layouts and allocation maps (Lower Level Access)')),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
