# Generated by Django 4.2.9 on 2026-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermgmt", "0002_delete_rbacpermissionproxy_rbacpermissionproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
