# Generated by Django 6.0.5 on 2026-05-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='gaurav_user',
        ),
    ]
