# Generated by Django 6.0.5 on 2026-05-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_alter_user_id'),
        ('usermgmt', '0005_alter_user_table'),
    ]

    operations = [
    ]
