# Generated by Django 6.0.5 on 2026-05-29 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GateApprovalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_client', models.CharField(blank=True, max_length=255)),
                ('mt_course_registration', models.CharField(blank=True, max_length=255)),
                ('number_of_participants', models.IntegerField(default=0)),
                ('training_type_online_offline', models.CharField(blank=True, max_length=50)),
                ('training_need_type', models.CharField(blank=True, max_length=100)),
                ('training_need_content', models.TextField(blank=True)),
                ('prep_sta_infra', models.CharField(blank=True, max_length=255)),
                ('prep_consumables', models.CharField(blank=True, max_length=255)),
                ('prep_ctea_infra', models.CharField(blank=True, max_length=255)),
                ('prep_mt_availability', models.CharField(blank=True, max_length=255)),
                ('prep_material', models.CharField(blank=True, max_length=255)),
                ('prep_material_ppt', models.CharField(blank=True, max_length=255)),
                ('prep_feedback', models.CharField(blank=True, max_length=255)),
                ('session_plan_availability', models.CharField(blank=True, max_length=255)),
                ('value_addition', models.CharField(blank=True, max_length=255)),
                ('assessment_formative', models.CharField(blank=True, max_length=255)),
                ('assessment_summative', models.CharField(blank=True, max_length=255)),
                ('assessment_certification', models.CharField(blank=True, max_length=255)),
                ('assessment_assessors', models.CharField(blank=True, max_length=255)),
                ('invoicing_documents', models.CharField(blank=True, max_length=255)),
                ('fees_standard_deviations', models.CharField(blank=True, max_length=255)),
                ('challenges_mitigation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending Marketing Approval', 'Pending Marketing Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Marketing Approval', max_length=50)),
                ('marketing_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_approval', to='proposalmgmt.futureproposal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gate_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_gate_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GateZeroForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_training_room_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('is_hostel_facility_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('is_trainer_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('is_proposal_financially_feasible', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_zero', to='proposalmgmt.futureproposal')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_gate_zeros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
