"""
Django settings for pravaah project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================================
# 1. SECURITY & DEVELOPMENT ENVIRONMENT SETTINGS
# =========================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gx5qe+sn%shg@r*tb0s!7rha#74w$+h+*!#+4t*flo-ar_=46t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# =========================================================================
# 2. APPLICATION & MIDDLEWARE DEFINITIONS
# =========================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Unified Module Registration Workspace
    'usermgmt',
    'billingmgmt',
    'proposalmgmt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usermgmt.middleware.RoleBasedAccessControlMiddleware',
]

ROOT_URLCONF = 'pravaah.urls'
WSGI_APPLICATION = 'pravaah.wsgi.application'


# =========================================================================
# 3. GRAPHICAL USER INTERFACE & TEMPLATE ENGINES
# =========================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Supports project-wide core global templates
        'APP_DIRS': True,                  # Looks inside usermgmt/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================================================================
# 4. DATABASE CONSTRAINTS & ROUTERS
# =========================================================================
DATABASES = {
    'default': {
       # 'ENGINE': 'django.db.backends.sqlite3',
       # 'NAME': BASE_DIR / 'db.sqlite3',
       
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pravaah',          # Your MySQL Database Name
        'USER': 'test',                # Your MySQL username
        'PASSWORD': 'Laptop@123',            # Your MySQL password
        'HOST': '192.168.0.95',           # Local PC IP (Change to server IP later)
        'PORT': '3306',                # Standard MySQL port
    }
}


# =========================================================================
# 5. PASSWORD VALIDATION POLICIES
# =========================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================================
# 6. INTERNATIONALIZATION & TIMEZONES
# =========================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =========================================================================
# 7. ASSET FLOW ENGINE (STATIC & MEDIA SCHEMAS)
# =========================================================================
# Static Assets Framework (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# User Media Upload Configuration Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================================
# 8. SYSTEM CONFIGURATION ROUTERS
# =========================================================================
# Directs the framework to map credentials against your integrated custom platform model
AUTH_USER_MODEL = 'usermgmt.User'

# Authentication fallback routing URL
LOGIN_URL = '/login/'
